---
namespace: amazon
name: ai
version: 2.0.0-dev0
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: Ansible Collection for Amazon AI and ML Resources
license_file: LICENSE
tags:
  - ai
  - amazon
  - cloud
dependencies:
  amazon.aws: '>=10.0.0'
repository: https://github.com/ansible-collections/amazon.ai
homepage: https://github.com/ansible-collections/amazon.ai
issues: https://github.com/ansible-collections/amazon.ai/issues
build_ignore:
  - changelogs/.plugin-cache.yaml
  - '*cloud-config-aws.ini'
  - '*cloud-config-aws.yml'
  - .ansible-lint
  - .github
  - pyproject.toml
  - test-requirements.txt
  - tox.ini
  - .yamllint
